/**
 * CLI Code Generation - URL-based code generation (weak types)
 */

import type { RpcSchema } from './types.js'

/**
 * Generate client type definition from runtime schema
 */
export function generateClient(schema: RpcSchema): string {
  const lines: string[] = ['// Generated by `npx rpc.do generate`', '// Do not edit manually', '', 'export interface GeneratedAPI {']

  // Top-level methods
  for (const method of schema.methods) {
    lines.push(`  ${method.name}(...args: any[]): Promise<any>`)
  }

  // Namespaces
  for (const ns of schema.namespaces) {
    lines.push(`  ${ns.name}: {`)
    for (const method of ns.methods) {
      lines.push(`    ${method.name}(...args: any[]): Promise<any>`)
    }
    lines.push(`  }`)
  }

  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

/**
 * Generate entrypoint file for URL-based generation
 */
export function generateEntrypoint(): string {
  return [
    '// Generated by `npx rpc.do generate`',
    '// Do not edit manually',
    '',
    "import { RPC, type Transport } from 'rpc.do'",
    "import type { GeneratedAPI } from './client'",
    '',
    '/**',
    ' * Create a typed RPC client',
    ' */',
    'export function createClient(transport: Transport) {',
    '  return RPC<GeneratedAPI>(transport)',
    '}',
    '',
    'export type { GeneratedAPI }',
    '',
  ].join('\n')
}
